/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GoldPrice {
  'lastUpdated' : Time,
  'pricePerGram' : bigint,
  'purity' : string,
}
export interface Inquiry {
  'name' : string,
  'message' : string,
  'timestamp' : Time,
  'productInterest' : string,
  'phone' : string,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'isActive' : boolean,
  'category' : string,
  'price' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [string, string, bigint, string, Array<string>],
    undefined
  >,
  'getActiveProducts' : ActorMethod<[], Array<Product>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getGoldPrices' : ActorMethod<[], Array<GoldPrice>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'submitInquiry' : ActorMethod<[string, string, string, string], undefined>,
  'updateGoldPrice' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];