/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const Time = IDL.Int;
export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'productInterest' : IDL.Text,
  'phone' : IDL.Text,
});
export const GoldPrice = IDL.Record({
  'lastUpdated' : Time,
  'pricePerGram' : IDL.Nat,
  'purity' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getGoldPrices' : IDL.Func([], [IDL.Vec(GoldPrice)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateGoldPrice' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'productInterest' : IDL.Text,
    'phone' : IDL.Text,
  });
  const GoldPrice = IDL.Record({
    'lastUpdated' : Time,
    'pricePerGram' : IDL.Nat,
    'purity' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getGoldPrices' : IDL.Func([], [IDL.Vec(GoldPrice)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateGoldPrice' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };